AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  multitranslator_api

  Backend API for MultiTranslator

Globals:
  Function:
    Timeout: 30

Resources:
  MultiTranslator:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: multitranslator/
      Handler: lambda_handler.lambda_handler
      Runtime: python3.9
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action: "translate:TranslateText"
              Resource: "*"
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref MultiTranslatorAPI
            Path: /translate
            Method: GET

  MultiTranslatorAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration: true
